version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbitmq-consume:
    restart: always
    build: .
    command: python rabbitmq-consume.py
    depends_on:
      - rabbitmq
